BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '01550' BEGIN END;
EXECUTE IMMEDIATE 'CREATE INDEX TXSTORE.LOTTERY_TX_HEADER_GLOBAL_TRANS_ID_START_DRAW_NUMBER
    on TXSTORE.LOTTERY_TX_HEADER (GLOBAL_TRANS_ID,START_DRAW_NUMBER,LOTTERY_TRANSACTION_TYPE)';
END
@
REORG INDEXES ALL FOR TABLE TXSTORE.LOTTERY_TX_HEADER
@