BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
    EXECUTE IMMEDIATE 'CREATE TABLE TXSTORE.MIGRATED_TX_DRAW_ENTRY(
                                    ID BIGINT NOT NULL,
                                    UUID VARCHAR(200) NOT NULL,
                                    DRAWNUMBER INTEGER NOT NULL,
                                    PRODUCT INTEGER NOT NULL,
                                    WIN_STATUS VARCHAR(50) NOT NULL,
                                    CONSTRAINT XPKMIGRATED_TX_DRAW_ENTRY PRIMARY KEY (ID))';
END
@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '01550' BEGIN END;
EXECUTE IMMEDIATE 'CREATE INDEX TXSTORE.IDXMIGRATED_TX_DRAW_ENTRY ON TXSTORE.MIGRATED_TX_DRAW_ENTRY ( UUID ASC )';
END
@
BEGIN
EXECUTE IMMEDIATE 'CREATE or REPLACE SEQUENCE TXSTORE.MIGRATED_TX_DRAW_ENTRY_SEQ INCREMENT BY 1 START WITH 1';
END
@