CREATE OR REPLACE VIEW TXSTORE.MIGRATED_TX_DRAW AS
SELECT
    E.IDDGGAMEEVENT,
    E.IDDGGAME,
    E.DRAWNUMBER,
    E.DRAWDATE
FROM TXSTORE.MIGRATED_TX_DRAW_ENTRY DE
         INNER JOIN GIS.DGGAMEEVENT E ON E.IDDGGAME=DE.PRODUCT AND E.DRAWNUMBER=DE.DRAWNUMBER
GROUP BY E.IDDGGAMEEVENT,E.IDDGGAME,E.DRAWNUMBER,E.DRAWDATE
@