BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
    EXECUTE IMMEDIATE 'create table TXSTORE.MIGR_TX_HEADER(
                       TX_HEADER_ID BIGINT not null constraint XPKMIGR_TX_HEADER primary key,
                       PLAYER_ID    BIGINT not null,
                       UUID         VARCHAR(200))';
END
@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '01550' BEGIN END;
EXECUTE IMMEDIATE 'create unique index TXSTORE.UQIDXMIGR_TX_HEADER
    on TXSTORE.MIGR_TX_HEADER (UUID)';
END
@
BEGIN DECLARE CONTINUE HANDLER FOR SQLSTATE '01550' BEGIN END;
EXECUTE IMMEDIATE 'create index TXSTORE.XIDXMIGR_TX_HEADERPLAYERID
    on TXSTORE.MIGR_TX_HEADER (PLAYER_ID)';
END
@