CREATE OR REPLACE VIEW TXSTORE.VIEW_MIGRATED_TX AS
    SELECT
        H.TX_HEADER_ID,
        L.GLOBAL_TRANS_ID,
        L.GLOBAL_TRANS_ID AS CORRELATION_ID,
        H.UUID,
        H.PLAYER_ID,
        L.TRANSACTION_TIME_UTC,
        L.LOTTERY_TRANSACTION_TYPE,
        L.TRANSACTION_AMOUNT,
        L.SERIAL,
        L.CDC,
        L.TRANSACTION_TIME_LOCAL,
        L.PRODUCT,
        L.START_DRAW_NUMBER,
        L.END_DRAW_NUMBER,
        B.DATA,
        L.SUBSCRIPTION_ID,
        L.JOURNAL_ADDRESS
    FROM TXSTORE.MIGR_TX_HEADER H
             INNER JOIN TXSTORE.LOTTERY_TX_HEADER L ON L.LOTTERY_TX_HEADER_ID=H.TX_HEADER_ID
             INNER JOIN TXSTORE.STRING_TX_BODY B ON B.UUID=H.UUID
@